language: node_js

sudo: required

node_js:
- v10.8.0

cache:
    directories:
    - node_modules

notifications:
    email:
        recipients:
        - guilherme.moraes@outlook.com
        on_success: never
        on_failure: always

services:
- rabbitmq

script:
- npm install
- npm run lint
- npm run build
- npm link
- nqr -a examples/amqp.yml -l enqueuer-plugin-amqp/enqueuer-plugin-amqp
